  services:
    postgres:
      image: postgres:15
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: postgres
      ports:
        - "5432:5432"
      volumes:
        - postgres_data:/var/lib/postgresql/data
    dynamodb:
      image: amazon/dynamodb-local
      container_name: dynamodb-local
      ports:
        - "8000:8000"
      command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."
  volumes:
    postgres_data:
